services:
  cafeordermanagementsystem.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
      - "8081"
    expose:
      - "8080"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=Password12*
      - ACCEPT_EULA=Y
    ports:
      - "1434:1433"
    
    volumes:
      - sql_data:/var/opt/mssql
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
volumes:
  sql_data: